// THE DATED PORTFOLIO NAV SERIES, and the one comparison it can honestly carry.
//
// `BOOK_NAV_HISTORY` is generated by `build-book.mjs` from the archive's own
// reissues — see `navHistoryFrom` there for how the points are struck and why
// this used to be an empty array with a note saying it could not exist. This
// module does the two things a PAGE needs on top of that: turn the levels into a
// return the book actually earned, and align that against an index.
//
// ── THE ONE THING THAT MAKES THIS COMPARISON MEAN ANYTHING ───────────────────
//
// Measured on this archive over 2026-07-10 → 2026-08-13, the covered set's NAV
// runs ₹128.25 Cr → ₹140.17 Cr. Charted straight against the Nifty 500 that is
// +9.29% against the index's +1.33% — eight points of outperformance, and NONE
// OF IT IS PERFORMANCE. ₹11.24 Cr of it is a Fund Deposit into V.E.C 128005 on
// 28 and 29 July. Net that out and the book earned +0.54% against the index's
// +1.33%, which is the answer.
//
// So the chart is drawn on a FLOW-ADJUSTED index and the raw NAV level is a
// separate, clearly-labelled line. This is the same failure `accountXirr.test.ts`
// already gates for on that very account — a rupee-left-alone figure cannot see
// a deposit and a NAV can — arriving one measurement over.
//
// AND THE ADJUSTMENT IS ONLY CLAIMED WHERE IT WAS MEASURED. Four covered
// accounts publish no dated capital record and hold more than one security, so a
// subscription inside one of them would read here as performance. Their value is
// carried in `unreportedFlowValue` per point and named on screen. That is not a
// disclaimer bolted on: it is the difference between "the book returned +0.54%"
// and "the book's marks moved +0.54% and ₹28.3 Cr of that move is unproven".
import type { NavPoint, NavCoverage, Portfolio } from "./types";
import type { Point } from "./series";

export type NavIndexPoint = {
  date: string;
  /** The consolidated NAV as the statements stood, in base currency. */
  nav: number;
  /** Net external capital in since the previous point. */
  flowIn: number;
  /** The flow-adjusted index, 100 at the first point. */
  index: number;
  /** The raw NAV rebased to 100 — the same curve the index corrects. */
  navIndex: number;
  accountsOnDate: number;
  accountsCarried: number;
  unreportedFlowValue: number;
};

/**
 * Chain each interval's return NET OF THE CAPITAL THAT ENTERED IT.
 *
 *   r = (NAV_end − flowIn) / NAV_start − 1
 *
 * `flowIn` is attributed by the generator to the interval in which the RECEIVING
 * ACCOUNT's mark moves, not the interval the money arrived in — a carried-forward
 * account's flows and its marks run on different clocks, and subtracting a
 * deposit from a NAV that has not yet been restated to include it produces a
 * large false loss followed by a large false gain. See `navHistoryFrom`.
 *
 * An interval whose starting NAV is not positive yields no return rather than a
 * division: an index cannot be chained through zero, and inventing 0% there
 * would be a measurement nothing made.
 */
export function navIndexSeries(history: NavPoint[]): NavIndexPoint[] {
  if (history.length < 2) return [];
  const out: NavIndexPoint[] = [];
  let idx = 100;
  const base = history[0].nav;
  for (let i = 0; i < history.length; i++) {
    const p = history[i];
    if (i > 0) {
      const prev = history[i - 1].nav;
      const flow = p.flowIn ?? 0;
      if (prev > 0) idx *= (p.nav - flow) / prev;
    }
    out.push({
      date: p.date,
      nav: p.nav,
      flowIn: p.flowIn ?? 0,
      index: idx,
      navIndex: base > 0 ? (p.nav / base) * 100 : 100,
      accountsOnDate: p.accountsOnDate ?? 0,
      accountsCarried: p.accountsCarried ?? 0,
      unreportedFlowValue: p.unreportedFlowValue ?? 0,
    });
  }
  return out;
}

/**
 * The index's level on each of the book's own dates, rebased to the same 100.
 *
 * NEAREST-EARLIER, NEVER NEAREST. A book date is a statement date and an index
 * date is a trading session; 2026-07-27 is a Monday the Nifty 500 traded and
 * 2026-08-13 is not always. Taking the nearest close in EITHER direction would
 * credit the index with a move that had not happened when the statement was
 * struck — the same look-ahead `computeReturns` avoids by excluding today's
 * in-progress bar. A book date earlier than the index's own first close yields
 * nothing rather than the first close, which would flatten the start.
 */
export function alignIndex(indexPoints: Point[], dates: string[]): { date: string; level: number }[] {
  if (!indexPoints.length) return [];
  const sorted = [...indexPoints].sort((a, b) => (a.t < b.t ? -1 : a.t > b.t ? 1 : 0));
  const out: { date: string; level: number }[] = [];
  let i = 0;
  let last: Point | null = null;
  for (const d of dates) {
    while (i < sorted.length && sorted[i].t <= d) { last = sorted[i]; i++; }
    if (last) out.push({ date: d, level: last.v });
  }
  return out;
}

/** `alignIndex`, rebased to 100 at the first aligned point. */
export function rebasedIndex(indexPoints: Point[], dates: string[]): Map<string, number> {
  const aligned = alignIndex(indexPoints, dates);
  const out = new Map<string, number>();
  if (!aligned.length || !(aligned[0].level > 0)) return out;
  const base = aligned[0].level;
  for (const a of aligned) out.set(a.date, (a.level / base) * 100);
  return out;
}

export type NavCoverageStats = {
  /** Accounts carrying two or more dated valuations — the series' own set. */
  coveredCount: number;
  coveredValue: number;
  /** Accounts publishing exactly ONE dated valuation: a level, never a change. */
  singleCount: number;
  singleValue: number;
  /** Accounts no statement values at all. */
  unvaluedCount: number;
  unvaluedValue: number;
  /** Every account in the book, as the three lists account for it. */
  accountsTotal: number;
  perAccountValue: number;
  /**
   * The book's CONSOLIDATED total. It is BELOW `perAccountValue` by exactly the
   * value reported under two members, because a per-account sum does not dedupe
   * and a consolidated one does. Both are carried so the page can state the gap
   * rather than let a reader find it by adding.
   */
  consolidatedValue: number;
  /** Covered accounts whose capital movements are not reported anywhere. */
  unreportedFlowAccounts: string[];
  unreportedFlowValue: number;
};

export function navCoverageStats(coverage: NavCoverage, portfolio: Portfolio | null): NavCoverageStats {
  const sum = (xs: number[]) => xs.reduce((a, b) => a + b, 0);
  const coveredValue = sum(coverage.covered.map((c) => c.bookValue));
  const singleValue = sum(coverage.single.map((c) => c.bookValue));
  const unvaluedValue = sum(coverage.unvalued.map((c) => c.bookValue));
  const unreported = coverage.covered.filter((c) => c.flowBasis === "unreported");
  return {
    coveredCount: coverage.covered.length,
    coveredValue,
    singleCount: coverage.single.length,
    singleValue,
    unvaluedCount: coverage.unvalued.length,
    unvaluedValue,
    accountsTotal: coverage.covered.length + coverage.single.length + coverage.unvalued.length,
    perAccountValue: coveredValue + singleValue + unvaluedValue,
    consolidatedValue: portfolio?.totalValue ?? 0,
    unreportedFlowAccounts: unreported.map((c) => c.accountId),
    unreportedFlowValue: sum(unreported.map((c) => c.bookValue)),
  };
}

/** Whole-window return of a chained index, in percent. Null on an empty series. */
export function windowReturnPct(points: { index: number }[]): number | null {
  if (points.length < 2) return null;
  return points[points.length - 1].index - 100;
}
