// THE DATED PORTFOLIO NAV SERIES, and the one comparison it can honestly carry.
//
// `BOOK_NAV_HISTORY` is generated by `build-book.mjs` from the archive's own
// reissues — see `navHistoryFrom` there for how the points are struck and why
// this used to be an empty array with a note saying it could not exist. This
// module does the two things a PAGE needs on top of that: turn the levels into a
// return the book actually earned, and align that against an index.
//
// ── THE ONE THING THAT MAKES THIS COMPARISON MEAN ANYTHING ───────────────────
//
// Measured on this archive over 2026-07-10 → 2026-08-13, the covered set's NAV
// runs ₹128.25 Cr → ₹140.17 Cr. Charted straight against the Nifty 500 that is
// +9.29% against the index's +1.33% — eight points of outperformance, and NONE
// OF IT IS PERFORMANCE. ₹11.24 Cr of it is a Fund Deposit into V.E.C 128005 on
// 28 and 29 July. Net that out and the book earned +0.54% against the index's
// +1.33%, which is the answer.
//
// So the chart is drawn on a FLOW-ADJUSTED index and the raw NAV level is a
// separate, clearly-labelled line. This is the same failure `accountXirr.test.ts`
// already gates for on that very account — a rupee-left-alone figure cannot see
// a deposit and a NAV can — arriving one measurement over.
//
// AND THE ADJUSTMENT IS ONLY CLAIMED WHERE IT WAS MEASURED. A step between two
// of an account's marks that no statement settles — no printed capital total at
// both ends, no identical unit counts, no dated record — would carry a
// subscription as performance, so its MOVE is carried in `unreportedFlowValue`
// per point and named on screen. It said "₹28.3 Cr of that move is unproven"
// here for as long as the builder read one table for proof: that was the VALUE
// of four accounts, ten times what they moved, and their own statements settle
// every step (A-10). On this archive no step is unproven.
import type { NavPoint, NavCoverage, Portfolio } from "./types";
import type { Point } from "./series";

export type NavIndexPoint = {
  date: string;
  /** The consolidated NAV as the statements stood, in base currency. */
  nav: number;
  /** Net external capital in since the previous point. */
  flowIn: number;
  /** The flow-adjusted index, 100 at the first point. */
  index: number;
  /**
   * The raw NAV — capital left in — scaled to start ON the book's own index
   * where the panel completes, so the distance between the two lines after that
   * date is the capital the book's line nets out. NaN before the panel is
   * complete, where the level is a growing set of accounts.
   */
  navIndex: number;
  accountsOnDate: number;
  accountsCarried: number;
  unreportedFlowValue: number;
  /** How many accounts the link ending at this point was struck over. */
  linkAccounts: number;
  /** True once every covered account has published — see `NavPoint`. */
  panelComplete: boolean;
};

/**
 * Chain each interval's return NET OF THE CAPITAL THAT ENTERED IT.
 *
 *   r = (NAV_end − flowIn) / NAV_start − 1
 *
 * `flowIn` is attributed by the generator to the interval in which the RECEIVING
 * ACCOUNT's mark moves, not the interval the money arrived in — a carried-forward
 * account's flows and its marks run on different clocks, and subtracting a
 * deposit from a NAV that has not yet been restated to include it produces a
 * large false loss followed by a large false gain. See `navHistoryFrom`.
 *
 * An interval whose starting NAV is not positive yields no return rather than a
 * division: an index cannot be chained through zero, and inventing 0% there
 * would be a measurement nothing made.
 */
export function navIndexSeries(history: NavPoint[]): NavIndexPoint[] {
  if (history.length < 2) return [];
  const out: NavIndexPoint[] = [];
  let idx = 100;
  /**
   * THE RAW NAV LINE IS REBASED AT THE COMPLETE PANEL, NOT AT THE FIRST POINT.
   *
   * `nav` is the whole marked panel, and the panel GROWS: ₹25.85 Cr over four
   * accounts on 31 May against ₹128.25 Cr over thirteen on 10 July. Rebasing
   * that to the first point draws a line up 396% in six weeks, every rupee of
   * it an arrival. So the raw line starts where the panel is complete and is
   * undefined before it — the one thing a chain-link cannot rescue, because it
   * is a LEVEL rather than a return.
   */
  const firstComplete = history.find((p) => p.panelComplete !== false);
  const base = firstComplete ? firstComplete.nav : history[0].nav;
  /**
   * …AND IT STARTS ON THE BOOK'S LINE, NOT AT ITS OWN 100 (MNT-12).
   *
   * The raw line used to be rebased to 100 at the complete panel while the
   * book's line is 100 at the series' first point, so on one chart the two
   * sat on different bases: at 13 Aug the gap between them read 4.2 points
   * where the capital the raw line leaves in is worth 8.75, and the tooltip
   * printed a +9.29% (from 10 Jul) beside a +5.09% (from 31 May) with nothing
   * saying they are two windows. Anchored on the book's own index at the date
   * the panel completes, the two lines meet there and every point of distance
   * after it is the capital left in. `anchor` is 100 where the panel is
   * complete from the first point, so an older book draws what it always did.
   */
  let anchor = 100;
  for (let i = 0; i < history.length; i++) {
    const p = history[i];
    if (i > 0) {
      /**
       * CHAINED ON THE LINK, NOT ON THE LEVEL.
       *
       * `linkOpen` and `linkClose` are struck over the accounts valued at BOTH
       * ends of this interval, so an account arriving here is in neither and
       * contributes nothing. Dividing `nav` by the previous `nav` instead would
       * put every arrival into the return, which is why the generator used to
       * refuse to emit these points at all. Where the generator emits no link —
       * an older book, or a first point — the level is the fallback and is
       * identical once the panel is complete.
       */
      const open = p.linkOpen ?? history[i - 1].nav;
      const close = p.linkClose ?? p.nav;
      const flow = p.flowIn ?? 0;
      if (open > 0) idx *= (close - flow) / open;
    }
    if (p === firstComplete) anchor = idx;
    out.push({
      date: p.date,
      nav: p.nav,
      flowIn: p.flowIn ?? 0,
      index: idx,
      navIndex: p.panelComplete === false || base <= 0 ? NaN : (p.nav / base) * anchor,
      accountsOnDate: p.accountsOnDate ?? 0,
      accountsCarried: p.accountsCarried ?? 0,
      unreportedFlowValue: p.unreportedFlowValue ?? 0,
      linkAccounts: p.linkAccounts ?? (p.accountsOnDate ?? 0) + (p.accountsCarried ?? 0),
      panelComplete: p.panelComplete !== false,
    });
  }
  return out;
}

/**
 * The index's last close ON OR BEFORE a date — the one lookup every alignment
 * here is built on, so the chart, the pills and the aligned points cannot
 * disagree about which close a date resolves to.
 *
 * Null before the index's own first close, never its first close: a book date
 * that predates the series has no level, and substituting the earliest one
 * would flatten the start of the curve and print a 0% first interval that
 * nothing measured.
 */
export function levelOnOrBefore(sorted: Point[], date: string): number | null {
  let out: number | null = null;
  for (const p of sorted) {
    if (p.t > date) break;
    out = p.v;
  }
  return out;
}

/** Ascending by date, so every lookup above can walk once and stop. */
export function sortPoints(points: Point[]): Point[] {
  return [...points].sort((a, b) => (a.t < b.t ? -1 : a.t > b.t ? 1 : 0));
}

/**
 * THE INDEX AS ITS OWN DAILY CURVE, rebased at the book's first dated point.
 *
 * `rebasedIndex` below samples the index at the BOOK's seven dates, which is
 * what the pills need and is the wrong thing to draw: seven straight segments
 * across five weeks is not the index's path, and over a year of context it would
 * be four. This returns every settled close the feed carries inside the window,
 * so the line the reader sees is the market's own.
 *
 * THE BASE IS THE BOOK'S FIRST POINT AND NOT THE WINDOW'S. That is deliberate
 * and it is the only base at which the comparison is exact: both lines pass
 * through 100 on the one date both measurements exist for. A curve rebased to
 * the left edge of a five-year window would put the book's line at whatever
 * level the index happened to reach by July and invite a reader to compare two
 * numbers struck from different starts.
 */
export function indexCurve(points: Point[], baseDate: string, fromDate: string | null): Point[] {
  const sorted = sortPoints(points);
  const base = levelOnOrBefore(sorted, baseDate);
  if (base == null || !(base > 0)) return [];
  const out: Point[] = [];
  for (const p of sorted) {
    if (fromDate && p.t < fromDate) continue;
    out.push({ t: p.t, v: (p.v / base) * 100 });
  }
  return out;
}

/**
 * The index's return between two dates, each resolved NEAREST-EARLIER.
 *
 * Used for the like-for-like pill (the index over the book's own window) and for
 * the selected range's own figure, which is index-only and is labelled as such.
 * Null where either end predates the index's first close, rather than a return
 * measured from a date the feed does not cover.
 */
export function indexReturnBetween(points: Point[], from: string, to: string): number | null {
  const sorted = sortPoints(points);
  const a = levelOnOrBefore(sorted, from);
  const b = levelOnOrBefore(sorted, to);
  if (a == null || b == null || !(a > 0)) return null;
  return (b / a - 1) * 100;
}

/**
 * ── HOW FAR BACK THE CHART LOOKS ────────────────────────────────────────────
 *
 * The family asked for a larger period than the book's own five weeks, and the
 * honest answer is asymmetric: the INDEX has years of daily closes and the BOOK
 * has what its statements carry. So the range governs the index's context and
 * the book draws where it is measured — with the measured window shaded, so a
 * reader on the five-year view can see at a glance which stretch of the chart
 * carries a comparison and which is market history alone.
 *
 * `days: 0` is the book's own span rather than a duration, so the default view
 * is exactly the window in which both lines exist.
 */
export type NavRangeKey = "book" | "3M" | "6M" | "1Y" | "3Y" | "5Y" | "MAX";

export const NAV_RANGES: { key: NavRangeKey; label: string; days: number | null }[] = [
  { key: "book", label: "Book window", days: 0 },
  { key: "3M", label: "3M", days: 91 },
  { key: "6M", label: "6M", days: 183 },
  { key: "1Y", label: "1Y", days: 365 },
  { key: "3Y", label: "3Y", days: 365 * 3 },
  { key: "5Y", label: "5Y", days: 365 * 5 },
  { key: "MAX", label: "Max", days: null },
];

/**
 * The window's first date, counted BACK FROM THE BOOK'S LAST DATED POINT.
 *
 * Anchored on the book rather than on today so the shaded measured window keeps
 * its place as the range widens, and so a range does not silently shrink the
 * comparison because three weeks have passed since the last statement.
 */
export function rangeStart(range: NavRangeKey, bookFrom: string, bookTo: string): string | null {
  const days = NAV_RANGES.find((r) => r.key === range)?.days;
  if (days === null || days === undefined) return null;
  if (days === 0) return bookFrom;
  const d = new Date(`${bookTo}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString().slice(0, 10);
}

/**
 * The window's last date, and only the book range has one.
 *
 * On every other range the index is drawn to its own last settled close, which
 * is weeks past the last statement and is the useful half of asking for a longer
 * period — where the market has gone since the book was last marked. The BOOK
 * range is the exception because its label promises the window both lines cover,
 * and an index line running three weeks past the book's final point would make
 * that label false. A control that describes itself wrongly is the same defect
 * as a caption that does.
 */
export function rangeEnd(range: NavRangeKey, bookTo: string): string | null {
  return range === "book" ? bookTo : null;
}

/**
 * The index's level on each of the book's own dates, rebased to the same 100.
 *
 * NEAREST-EARLIER, NEVER NEAREST. A book date is a statement date and an index
 * date is a trading session; 2026-07-27 is a Monday the Nifty 500 traded and
 * 2026-08-13 is not always. Taking the nearest close in EITHER direction would
 * credit the index with a move that had not happened when the statement was
 * struck — the same look-ahead `computeReturns` avoids by excluding today's
 * in-progress bar. A book date earlier than the index's own first close yields
 * nothing rather than the first close, which would flatten the start.
 */
export function alignIndex(indexPoints: Point[], dates: string[]): { date: string; level: number }[] {
  if (!indexPoints.length) return [];
  const sorted = sortPoints(indexPoints);
  const out: { date: string; level: number }[] = [];
  let i = 0;
  let last: Point | null = null;
  for (const d of dates) {
    while (i < sorted.length && sorted[i].t <= d) { last = sorted[i]; i++; }
    if (last) out.push({ date: d, level: last.v });
  }
  return out;
}

/** `alignIndex`, rebased to 100 at the first aligned point. */
export function rebasedIndex(indexPoints: Point[], dates: string[]): Map<string, number> {
  const aligned = alignIndex(indexPoints, dates);
  const out = new Map<string, number>();
  if (!aligned.length || !(aligned[0].level > 0)) return out;
  const base = aligned[0].level;
  for (const a of aligned) out.set(a.date, (a.level / base) * 100);
  return out;
}

export type NavCoverageStats = {
  /** Accounts carrying two or more dated valuations — the series' own set. */
  coveredCount: number;
  coveredValue: number;
  /** Accounts publishing exactly ONE dated valuation: a level, never a change. */
  singleCount: number;
  singleValue: number;
  /** Accounts no statement values at all. */
  unvaluedCount: number;
  unvaluedValue: number;
  /** Every account in the book, as the three lists account for it. */
  accountsTotal: number;
  perAccountValue: number;
  /**
   * The book's CONSOLIDATED total ON THE STATEMENT BASIS — the portfolio the
   * caller passes, which must be `statementPortfolio` wherever it is set beside
   * a series level (MNT-25). The series is struck on statement marks, so a
   * NAV-overlaid or live total as its denominator divides one basis by another;
   * on this drop the live book also carries funds valued from depository units
   * that no statement marks at all. It is BELOW `perAccountValue` by exactly
   * the value reported under two members, because a per-account sum does not
   * dedupe and a consolidated one does.
   */
  consolidatedValue: number;
  /** Covered accounts with a step no statement settles — see `NavPoint.unreportedFlowValue` for its move. */
  unreportedFlowAccounts: string[];
};

export function navCoverageStats(coverage: NavCoverage, portfolio: Portfolio | null): NavCoverageStats {
  const sum = (xs: number[]) => xs.reduce((a, b) => a + b, 0);
  const coveredValue = sum(coverage.covered.map((c) => c.bookValue));
  const singleValue = sum(coverage.single.map((c) => c.bookValue));
  const unvaluedValue = sum(coverage.unvalued.map((c) => c.bookValue));
  const unreported = coverage.covered.filter((c) => c.flowBasis === "unreported");
  return {
    coveredCount: coverage.covered.length,
    coveredValue,
    singleCount: coverage.single.length,
    singleValue,
    unvaluedCount: coverage.unvalued.length,
    unvaluedValue,
    accountsTotal: coverage.covered.length + coverage.single.length + coverage.unvalued.length,
    perAccountValue: coveredValue + singleValue + unvaluedValue,
    consolidatedValue: portfolio?.totalValue ?? 0,
    unreportedFlowAccounts: unreported.map((c) => c.accountId),
  };
}

/** Whole-window return of a chained index, in percent. Null on an empty series. */
export function windowReturnPct(points: { index: number }[]): number | null {
  if (points.length < 2) return null;
  return points[points.length - 1].index - 100;
}

/**
 * ── A REDEEMED ACCOUNT IS A MEASURED NIL, NOT AN ABSENT VALUATION (MNT-14) ──
 *
 * The coverage list of accounts that "publish no valuation at all" mixes two
 * different facts: folios nothing values (an angel fund with no NAV, a custody
 * account at face value, a demat whose holding statement is missing) and
 * accounts whose own holding statement says every holding has been REDEEMED.
 * The second is a balance of zero that a statement struck, and §2 forbids it
 * looking like the first — it drew a dash under "That is an absent valuation,
 * not a measured zero" for two accounts whose own reason says the opposite.
 *
 * `build-book` records the distinction only in the sentence it writes on the
 * account, so this reads that sentence's own clause. It is TIED TO ITS
 * GENERATOR: `navCard.test.ts` asserts the clause appears verbatim in
 * `scripts/build-book.mjs`, so rewording the branch there fails the suite
 * rather than quietly turning two measured nils back into absences.
 */
export const MEASURED_NIL_CLAUSE = "has been redeemed — the balance is nil, and that is a measurement";

export function isMeasuredNilAccount(a: { noPositionsReason?: string | null } | null | undefined): boolean {
  return !!a?.noPositionsReason && a.noPositionsReason.includes(MEASURED_NIL_CLAUSE);
}
