// THE FAMILY'S CONSOLIDATED REVIEW — its private-market lines, as it prints them.
//
// `src/data/reviewPrivate.ts` is GENERATED by `npm run build-review-private` from
// the review workbook in `source/august-2026-d/` (MOPWM, as on 30 June 2026). The
// family asked on 5 Oct 2026 for the private-market data to be shown from that
// sheet. Its figures are the REVIEW'S, at the review's own date, and most of them
// are at COST — so the generated module is read by the Private Market page's
// review tab and nowhere else, and nothing here reaches `glowData.ts`, the NAV or
// any statement total. Removing the tab removes every figure.
//
// Everything below is pure: it adds up what the generator emitted and never
// strikes a figure of its own.

import { sumOrNull } from "@/lib/analytics";

export interface ReviewStatement {
  accountId: string;
  owner: string;
  provider: string;
  accountNo: string;
  units: number | null;
  /** The book carries a market value for this statement row. */
  valued: boolean;
}

export interface ReviewDates {
  from: string | null;
  to: string | null;
  precision: "day" | "month" | "unread";
  printed: string;
  text: string;
}

export interface ReviewRow {
  key: string;
  name: string;
  /** The review tab the line is printed on. */
  tab: string;
  row: number;
  /**
   * The review's "Date Investment Range" cell: the day or the months it names, as
   * ISO, and `text`, the one form the page and the report print. `printed` is the
   * cell as the workbook carries it, whitespace collapsed — a single date is an
   * Excel serial there.
   */
  dates: ReviewDates | null;
  /** The review's own "Investment at Cost". */
  invested: number | null;
  /** What the review's own dated rows say was paid in — Transactions since inception. */
  paidIn: number | null;
  /** Income and sale proceeds on those rows. */
  paidBack: number | null;
  /** The review's own market value. */
  value: number | null;
  /** value + paid back − paid in; null where the line is held at cost. */
  gain: number | null;
  atCost: boolean;
  /** gain ÷ paid in, re-derived. */
  ret: number | null;
  /** What the review prints under Scheme Absolute %. */
  reviewRet: number | null;
  xirr: number | null;
  reviewXirr: number | null;
  benchmark: string | null;
  /** The review's own note on how the line is valued. */
  valuedAsOf: string | null;
  /** The first and last dated row on Transactions since inception (ISO). */
  since: string | null;
  until: string | null;
  /** What the return is struck on: the line's own dated rows, or — where it has none — the review's cost. */
  retBasis: "rows" | "cost" | null;
  remark?: string | null;
  /** A line now listed: where the review's Equity tab carries it. */
  equityTab?: { row: number; units: number | null; cost: number | null; value: number | null } | null;
  statements: ReviewStatement[];
  /** What licenses the join to this book's statements. */
  why: string | null;
}

export type ReviewSectionKey = "pe-funds" | "unlisted" | "pre-ipo" | "at-cost" | "now-listed" | "written-off" | "credit";

export interface ReviewSection {
  key: ReviewSectionKey;
  title: string;
  tab: string;
  /** The review's own head row for the block, where it prints one. */
  head: { row: number; invested: number; value: number } | null;
  rows: ReviewRow[];
}

export interface ReviewMember {
  name: string;
  peFunds: number | null;
  unlisted: number | null;
  peAtCost: number | null;
}

export interface ReviewCheck {
  key: string;
  /** The face: a few words. */
  short: string;
  text: string;
  detail: string;
}

export interface ReviewPrivate {
  workbook: string;
  asOf: string;
  basis: string | null;
  sections: ReviewSection[];
  privateInvestmentsTotal: { row: number; invested: number; value: number };
  members: ReviewMember[];
  membersRow: { peFunds: number; unlisted: number; peAtCost: number };
  checks: ReviewCheck[];
  refused: { line: string; why: string }[];
}

export interface ReviewTotals {
  lines: number;
  invested: number | null;
  investedOf: number;
  paidIn: number | null;
  paidInOf: number;
  paidBack: number | null;
  value: number | null;
  valueOf: number;
  gain: number | null;
  gainOf: number;
}

/** Sums over rows, each figure over the rows that carry it — never a missing one as zero. */
export function reviewTotals(rows: ReviewRow[]): ReviewTotals {
  const has = (f: (r: ReviewRow) => number | null) => rows.filter((r) => f(r) !== null).length;
  return {
    lines: rows.length,
    invested: sumOrNull(rows.map((r) => r.invested)),
    investedOf: has((r) => r.invested),
    paidIn: sumOrNull(rows.map((r) => r.paidIn)),
    paidInOf: has((r) => r.paidIn),
    paidBack: sumOrNull(rows.map((r) => r.paidBack)),
    value: sumOrNull(rows.map((r) => r.value)),
    valueOf: has((r) => r.value),
    gain: sumOrNull(rows.map((r) => r.gain)),
    gainOf: has((r) => r.gain),
  };
}

/** The review's own Investorwise figure for one member: PE funds + unlisted, at value, and private equity at cost. */
export const memberTotal = (m: ReviewMember): number | null => sumOrNull([m.peFunds, m.unlisted, m.peAtCost]);

/** Every line of the review's private-market data this tab draws. */
export const allReviewRows = (d: ReviewPrivate): ReviewRow[] => d.sections.flatMap((s) => s.rows);

/** The sections the review's own Investorwise summary sums — K M Global is filed under Debt there. */
export const SUMMARY_SECTIONS: readonly ReviewSectionKey[] = ["pe-funds", "unlisted", "pre-ipo", "at-cost", "now-listed", "written-off"];

/** Who holds a line, as its statements say: first names, once each. */
export function statementOwners(r: ReviewRow): string[] {
  const seen: string[] = [];
  for (const s of r.statements) {
    const label = s.owner.startsWith("Bharat Jaisinghani Family Trust") ? s.owner.replace("Bharat Jaisinghani Family ", "") : s.owner.split(" ")[0];
    if (!seen.includes(label)) seen.push(label);
  }
  return seen;
}
