/**
 * ── ONE SCHEME, ONE NAME ON SCREEN ─────────────────────────────────────────
 *
 *   *"why should everywhere you show me direct plan growth? You're wasting a
 *    space here. We don't need it… Maybe you can write direct. Just direct
 *    plan, growth option — remove… Rather, I would rather have WhiteOak multi
 *    asset… For example, BNDH L&MC is large and mid cap. Now it's very
 *    important, Bandhan, large and mid cap should come… So we are leaving a lot
 *    to imagination. So we'll have to be careful with the labels."*
 *
 * A depository clips a scheme name to its own column width and an AMC folio
 * spells the plan out at length. Both are what the statement printed, and
 * neither is a name a reader can act on.
 *
 * `src/data/schemeNames.json` is generated by `npm run build-scheme-names` from
 * `public/lookthrough/`, where every scheme was resolved from the book's own
 * ISIN — and, for a scheme that store has never seen, from AMFI's own daily
 * file on the ISIN the family's statement prints (Stage 10db). So the expansion
 * is AMFI's published name reached through an IDENTIFIER, never a resemblance —
 * see that script for the gates and `docs/SCHEME-NAMES.md` for every expansion
 * it publishes and every one it refuses.
 *
 * ── DISPLAY ONLY, ON THE SAME TERMS AS `stripDepositoryTail` ────────────────
 *
 * `securityKeyOf` is not routed through this and must never be. Helios Flexi
 * Cap reaches this book under TWO securityKeys — the AMC folio's and the
 * depository's clipped one — and after this change both READ ALIKE, because
 * they are one scheme. They are still two keys, two rows and two `/stock/`
 * pages, and `docs/BOOK-REPORT.md` still names them as the extractor join they
 * are. Merging them here would give a reader one tidy row and leave the
 * reconciler none the wiser, which is the failure this repo keeps naming: *if a
 * join fails, fix the EXTRACTOR.*
 *
 * ── THE PLAN STAYS, AND THAT IS NOT A HEDGE AGAINST THE ASK ────────────────
 *
 * *"Maybe you can write direct"* is the whole of what survives the strip: one
 * word, not "Direct Plan - Growth Option". It cannot be dropped altogether,
 * because **this book holds BOTH plans of two schemes** — HDFC Balanced
 * Advantage (`1273` / `1273-D`) and ICICI Pru Nifty Next 50 (`11889` /
 * `11889-D`). Plans differ in expense ratio and therefore in NAV, not in what
 * the fund owns, so without the word those are two rows with one name and two
 * different figures, which reads as a defect. The OPTION is dropped wherever it
 * is Growth, which is every scheme here, and says so where it is not.
 */
import schemeNames from "@/data/schemeNames.json";
import { displaySecurity } from "./format";

export type SchemeName = {
  /** AMFI's published name with the trailing plan/option phrase removed. */
  name: string;
  /** `Direct` / `Regular`, or null where the scheme names no plan (an ETF). */
  plan: string | null;
  /** Named only where it is not Growth — an IDCW folio is a different holding. */
  option: string | null;
  amc: string | null;
  isin: string;
  schemecode: string;
  /** AMFI's name as published, before the strip. */
  amfiName: string;
  /** What the family's own statement printed, so the two can be compared. */
  printed: string | null;
  /**
   * `isin`, `name` or `name+plan` — how `build-lookthrough` reached the scheme —
   * or `amfi-isin` where the look-through store never saw it and AMFI's own
   * daily file did, on the ISIN the family's statement prints (Stage 10db).
   */
  joinedBy: string | null;
};

const SCHEMES = schemeNames as Record<string, SchemeName>;

/** The resolved scheme for a holding's key, or null where none resolved. */
export function schemeNameFor(securityKey: string): SchemeName | null {
  return SCHEMES[securityKey] ?? null;
}

/** Every securityKey that resolves a scheme — for the checks and the report. */
export const SCHEME_KEYS: readonly string[] = Object.keys(SCHEMES);

/**
 * The label a reader sees for one holding.
 *
 * Falls through to `displaySecurity` — the depository-furniture strip and title
 * case — for everything that is not a resolved scheme, which is every company
 * share, every AIF folio and every PMS mandate in the book. A scheme that
 * resolved nothing keeps the name its statement printed and is named in
 * `docs/SCHEME-NAMES.md` rather than being matched to something it resembles.
 */
export function holdingLabel(securityKey: string, printedName: string): string {
  const s = SCHEMES[securityKey];
  return s ? composeSchemeLabel(s) : displaySecurity(printedName);
}

/**
 * The scheme's name plus the markers that distinguish it from its own twin.
 *
 * Exported because the daily-NAV movers card resolves a row by SCHEMECODE and
 * carries the store's own raw name (`Bandhan Large & Mid Cap Fund-Reg(G)`) as
 * its fallback — so it has to compose the label WITHOUT `displaySecurity`'s
 * title case, which renders `WhiteOak` as `Whiteoak`. One composition, two
 * callers, rather than a second spelling of one label.
 */
export function composeSchemeLabel(s: SchemeName): string {
  const marks = [s.plan, s.option].filter(Boolean);
  return marks.length ? `${s.name} · ${marks.join(" · ")}` : s.name;
}
