// GENERATED by `npm run build-upstox-instruments` — do not edit by hand.
//
// NSE trading symbol → the Upstox instrument that IS that security, taken from
// Upstox's own public instrument list and matched on the exact symbol or the
// book's own ISIN, never on a name. `functions/api/quotes.js` prices through
// it; `tradingSymbol` is what Upstox must echo back before a price is used.
//
// A map, not a figure: nothing here reaches `glowData.ts` or any total.

export const UPSTOX_INSTRUMENTS = Object.freeze({
 "AARTIDRUGS": {
  "key": "NSE_EQ|INE767A01016",
  "tradingSymbol": "AARTIDRUGS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ABCAPITAL": {
  "key": "NSE_EQ|INE674K01013",
  "tradingSymbol": "ABCAPITAL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "ALIVUS": {
  "key": "NSE_EQ|INE03Q201024",
  "tradingSymbol": "ALIVUS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "AMRUTANJAN": {
  "key": "NSE_EQ|INE098F01031",
  "tradingSymbol": "AMRUTANJAN",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ANUP": {
  "key": "NSE_EQ|INE294Z01018",
  "tradingSymbol": "ANUP",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ARVINDFASN": {
  "key": "NSE_EQ|INE955V01021",
  "tradingSymbol": "ARVINDFASN",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ATHERENERG": {
  "key": "NSE_EQ|INE0LEZ01016",
  "tradingSymbol": "ATHERENERG",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "AUROPHARMA": {
  "key": "NSE_EQ|INE406A01037",
  "tradingSymbol": "AUROPHARMA",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "AXISBANK": {
  "key": "NSE_EQ|INE238A01034",
  "tradingSymbol": "AXISBANK",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "BAJAJ-AUTO": {
  "key": "NSE_EQ|INE917I01010",
  "tradingSymbol": "BAJAJ-AUTO",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "BANCOINDIA": {
  "key": "NSE_EQ|INE213C01025",
  "tradingSymbol": "BANCOINDIA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BECTORFOOD": {
  "key": "NSE_EQ|INE495P01020",
  "tradingSymbol": "BECTORFOOD",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "BELRISE": {
  "key": "NSE_EQ|INE894V01022",
  "tradingSymbol": "BELRISE",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "BHEL": {
  "key": "NSE_EQ|INE257A01026",
  "tradingSymbol": "BHEL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BIOCON": {
  "key": "NSE_EQ|INE376G01013",
  "tradingSymbol": "BIOCON",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BIRLACABLE": {
  "key": "NSE_EQ|INE800A01015",
  "tradingSymbol": "BIRLACABLE",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "BLS": {
  "key": "NSE_EQ|INE153T01027",
  "tradingSymbol": "BLS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BLUEJET": {
  "key": "NSE_EQ|INE0KBH01020",
  "tradingSymbol": "BLUEJET",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BORORENEW": {
  "key": "NSE_EQ|INE666D01022",
  "tradingSymbol": "BORORENEW",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BPLPHARMA": {
  "key": "NSE_EQ|INE365Y01019",
  "tradingSymbol": "BPLPHARMA",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "BSOFT": {
  "key": "NSE_EQ|INE836A01035",
  "tradingSymbol": "BSOFT",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "BUILDPRO": {
  "key": "NSE_EQ|INE24OJ01011",
  "tradingSymbol": "BUILDPRO",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CANFINHOME": {
  "key": "NSE_EQ|INE477A01020",
  "tradingSymbol": "CANFINHOME",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CAPLIPOINT": {
  "key": "NSE_EQ|INE475E01026",
  "tradingSymbol": "CAPLIPOINT",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CEATLTD": {
  "key": "NSE_EQ|INE482A01020",
  "tradingSymbol": "CEATLTD",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CGCL": {
  "key": "NSE_EQ|INE180C01042",
  "tradingSymbol": "CGCL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "CHEMFAB": {
  "key": "NSE_EQ|INE783X01023",
  "tradingSymbol": "CHEMFAB",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CLEANMAX": {
  "key": "NSE_EQ|INE647U01026",
  "tradingSymbol": "CLEANMAX",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "CMLL": {
  "key": "NSE_EQ|INE11XY01018",
  "tradingSymbol": "CMLL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CNL": {
  "key": "NSE_EQ|INE985W01018",
  "tradingSymbol": "CNL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "CROMPTON": {
  "key": "NSE_EQ|INE299U01018",
  "tradingSymbol": "CROMPTON",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "CUB": {
  "key": "NSE_EQ|INE491A01021",
  "tradingSymbol": "CUB",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "DBL": {
  "key": "NSE_EQ|INE917M01012",
  "tradingSymbol": "DBL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "DCW": {
  "key": "NSE_EQ|INE500A01029",
  "tradingSymbol": "DCW",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "DEEPINDS": {
  "key": "NSE_EQ|INE0FHS01024",
  "tradingSymbol": "DEEPINDS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ECLERX": {
  "key": "NSE_EQ|INE738I01010",
  "tradingSymbol": "ECLERX",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "EDELWEISS": {
  "key": "NSE_EQ|INE532F01054",
  "tradingSymbol": "EDELWEISS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "EIHOTEL": {
  "key": "NSE_EQ|INE230A01023",
  "tradingSymbol": "EIHOTEL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "EMAPARTNER": {
  "key": "NSE_EQ|INE0ZOL01023",
  "tradingSymbol": "EMAPARTNER",
  "series": "SM",
  "joinedBy": "symbol+isin"
 },
 "EMIL": {
  "key": "NSE_EQ|INE02YR01019",
  "tradingSymbol": "EMIL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "ENGINERSIN": {
  "key": "NSE_EQ|INE510A01028",
  "tradingSymbol": "ENGINERSIN",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ESDS": {
  "key": "NSE_EQ|INE0DRI01029",
  "tradingSymbol": "ESDS",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "ESTER": {
  "key": "NSE_EQ|INE778B01029",
  "tradingSymbol": "ESTER",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "EUREKAFORB": {
  "key": "NSE_EQ|INE0KCE01017",
  "tradingSymbol": "EUREKAFORB",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "EXIDEIND": {
  "key": "NSE_EQ|INE302A01020",
  "tradingSymbol": "EXIDEIND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "FEDERALBNK": {
  "key": "NSE_EQ|INE171A01029",
  "tradingSymbol": "FEDERALBNK",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "FRACTAL": {
  "key": "NSE_EQ|INE212S01015",
  "tradingSymbol": "FRACTAL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "FUSION": {
  "key": "NSE_EQ|INE139R01012",
  "tradingSymbol": "FUSION",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GAEL": {
  "key": "NSE_EQ|INE036B01030",
  "tradingSymbol": "GAEL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "GATEWAY": {
  "key": "NSE_EQ|INE079J01017",
  "tradingSymbol": "GATEWAY",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GCHOTELS": {
  "key": "NSE_EQ|INE12E301017",
  "tradingSymbol": "GCHOTELS",
  "series": "SM",
  "joinedBy": "symbol+isin"
 },
 "GESHIP": {
  "key": "NSE_EQ|INE017A01032",
  "tradingSymbol": "GESHIP",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GHCL": {
  "key": "NSE_EQ|INE539A01019",
  "tradingSymbol": "GHCL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GHCLTEXTIL": {
  "key": "NSE_EQ|INE0PA801013",
  "tradingSymbol": "GHCLTEXTIL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GLAND": {
  "key": "NSE_EQ|INE068V01023",
  "tradingSymbol": "GLAND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GLENMARK": {
  "key": "NSE_EQ|INE935A01035",
  "tradingSymbol": "GLENMARK",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GMMPFAUDLR": {
  "key": "NSE_EQ|INE541A01023",
  "tradingSymbol": "GMMPFAUDLR",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GRAPHITE": {
  "key": "NSE_EQ|INE371A01025",
  "tradingSymbol": "GRAPHITE",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "GREAVESCOT": {
  "key": "NSE_EQ|INE224A01026",
  "tradingSymbol": "GREAVESCOT",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "HAL": {
  "key": "NSE_EQ|INE066F01020",
  "tradingSymbol": "HAL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "HDFCAMC": {
  "key": "NSE_EQ|INE127D01025",
  "tradingSymbol": "HDFCAMC",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "HEGAM": {
  "key": "NSE_EQ|INE545A01024",
  "tradingSymbol": "HEGAM",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ICICIBANK": {
  "key": "NSE_EQ|INE090A01021",
  "tradingSymbol": "ICICIBANK",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "ICIL": {
  "key": "NSE_EQ|INE483B01026",
  "tradingSymbol": "ICIL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "IEX": {
  "key": "NSE_EQ|INE022Q01020",
  "tradingSymbol": "IEX",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "IFBIND": {
  "key": "NSE_EQ|INE559A01017",
  "tradingSymbol": "IFBIND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "IMFA": {
  "key": "NSE_EQ|INE919H01018",
  "tradingSymbol": "IMFA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "INA": {
  "key": "NSE_EQ|INE0LGX01024",
  "tradingSymbol": "INA",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "INDIANB": {
  "key": "NSE_EQ|INE562A01011",
  "tradingSymbol": "INDIANB",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "INDRAMEDCO": {
  "key": "NSE_EQ|INE681B01017",
  "tradingSymbol": "INDRAMEDCO",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "INDUSINDBK": {
  "key": "NSE_EQ|INE095A01012",
  "tradingSymbol": "INDUSINDBK",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "INFINIUM": {
  "key": "NSE_EQ|INE0MRE01011",
  "tradingSymbol": "INFINIUM",
  "series": "ST",
  "joinedBy": "symbol+isin"
 },
 "INGERRAND": {
  "key": "NSE_EQ|INE177A01018",
  "tradingSymbol": "INGERRAND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "INTELLECT": {
  "key": "NSE_EQ|INE306R01017",
  "tradingSymbol": "INTELLECT",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ISGEC": {
  "key": "NSE_EQ|INE858B01029",
  "tradingSymbol": "ISGEC",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "J&KBANK": {
  "key": "NSE_EQ|INE168A01041",
  "tradingSymbol": "J&KBANK",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "JAMNAAUTO": {
  "key": "NSE_EQ|INE039C01032",
  "tradingSymbol": "JAMNAAUTO",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "JARO": {
  "key": "NSE_EQ|INE00YJ01010",
  "tradingSymbol": "JARO",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "JAYNECOIND": {
  "key": "NSE_EQ|INE854B01010",
  "tradingSymbol": "JAYNECOIND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "JPPOWER": {
  "key": "NSE_EQ|INE351F01018",
  "tradingSymbol": "JPPOWER",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "JSL": {
  "key": "NSE_EQ|INE220G01021",
  "tradingSymbol": "JSL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "JYOTHYLAB": {
  "key": "NSE_EQ|INE668F01031",
  "tradingSymbol": "JYOTHYLAB",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "KALYANKJIL": {
  "key": "NSE_EQ|INE303R01014",
  "tradingSymbol": "KALYANKJIL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "KARURVYSYA": {
  "key": "NSE_EQ|INE036D01028",
  "tradingSymbol": "KARURVYSYA",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "KAYNES": {
  "key": "NSE_EQ|INE918Z01012",
  "tradingSymbol": "KAYNES",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "KIRLFER": {
  "key": "NSE_EQ|INE884B01025",
  "tradingSymbol": "KIRLFER",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "KOVAI": {
  "key": "NSE_EQ|INE177F01017",
  "tradingSymbol": "KOVAI",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "KPIL": {
  "key": "NSE_EQ|INE220B01022",
  "tradingSymbol": "KPIL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "KSB": {
  "key": "NSE_EQ|INE999A01023",
  "tradingSymbol": "KSB",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "KSCL": {
  "key": "NSE_EQ|INE455I01029",
  "tradingSymbol": "KSCL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "LICI": {
  "key": "NSE_EQ|INE0J1Y01017",
  "tradingSymbol": "LICI",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "LIQUIDBEES": {
  "key": "NSE_EQ|INF732E01037",
  "tradingSymbol": "LIQUIDBEES",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "LUPIN": {
  "key": "NSE_EQ|INE326A01037",
  "tradingSymbol": "LUPIN",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "LXCHEM": {
  "key": "NSE_EQ|INE576O01020",
  "tradingSymbol": "LXCHEM",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "M&M": {
  "key": "NSE_EQ|INE101A01026",
  "tradingSymbol": "M&M",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "MASTEK": {
  "key": "NSE_EQ|INE759A01021",
  "tradingSymbol": "MASTEK",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "MIDHANI": {
  "key": "NSE_EQ|INE099Z01011",
  "tradingSymbol": "MIDHANI",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "MOTILALOFS": {
  "key": "NSE_EQ|INE338I01027",
  "tradingSymbol": "MOTILALOFS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "MPSLTD": {
  "key": "NSE_EQ|INE943D01017",
  "tradingSymbol": "MPSLTD",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "NAVNETEDUL": {
  "key": "NSE_EQ|INE060A01024",
  "tradingSymbol": "NAVNETEDUL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "NEULANDLAB": {
  "key": "NSE_EQ|INE794A01010",
  "tradingSymbol": "NEULANDLAB",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "NITINSPIN": {
  "key": "NSE_EQ|INE229H01012",
  "tradingSymbol": "NITINSPIN",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "NUVAMA": {
  "key": "NSE_EQ|INE531F01023",
  "tradingSymbol": "NUVAMA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "OBEROIRLTY": {
  "key": "NSE_EQ|INE093I01010",
  "tradingSymbol": "OBEROIRLTY",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ONESOURCE": {
  "key": "NSE_EQ|INE013P01021",
  "tradingSymbol": "ONESOURCE",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "PANACEABIO": {
  "key": "NSE_EQ|INE922B01023",
  "tradingSymbol": "PANACEABIO",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "PARAS": {
  "key": "NSE_EQ|INE045601023",
  "tradingSymbol": "PARAS",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "PARTH": {
  "key": "NSE_EQ|INE1H7V01011",
  "tradingSymbol": "PARTH",
  "series": "SM",
  "joinedBy": "symbol+isin"
 },
 "PFC": {
  "key": "NSE_EQ|INE134E01011",
  "tradingSymbol": "PFC",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "PGEL": {
  "key": "NSE_EQ|INE457L01029",
  "tradingSymbol": "PGEL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "PNB": {
  "key": "NSE_EQ|INE160A01022",
  "tradingSymbol": "PNB",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "POKARNA": {
  "key": "NSE_EQ|INE637C01025",
  "tradingSymbol": "POKARNA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "POLYPLEX": {
  "key": "NSE_EQ|INE633B01018",
  "tradingSymbol": "POLYPLEX",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "PRAJIND": {
  "key": "NSE_EQ|INE074A01025",
  "tradingSymbol": "PRAJIND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "PRICOLLTD": {
  "key": "NSE_EQ|INE726V01018",
  "tradingSymbol": "PRICOLLTD",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "PURVA": {
  "key": "NSE_EQ|INE323I01011",
  "tradingSymbol": "PURVA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "PVRINOX": {
  "key": "NSE_EQ|INE191H01014",
  "tradingSymbol": "PVRINOX",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "RATNAMANI": {
  "key": "NSE_EQ|INE703B01027",
  "tradingSymbol": "RATNAMANI",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "RBLBANK": {
  "key": "NSE_EQ|INE976G01028",
  "tradingSymbol": "RBLBANK",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "RECLTD": {
  "key": "NSE_EQ|INE020B01018",
  "tradingSymbol": "RECLTD",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SAGILITY": {
  "key": "NSE_EQ|INE0W2G01015",
  "tradingSymbol": "SAGILITY",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SANSERA": {
  "key": "NSE_EQ|INE953O01021",
  "tradingSymbol": "SANSERA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SBFC": {
  "key": "NSE_EQ|INE423Y01016",
  "tradingSymbol": "SBFC",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SBIN": {
  "key": "NSE_EQ|INE062A01020",
  "tradingSymbol": "SBIN",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "SGMART": {
  "key": "NSE_EQ|INE385F01024",
  "tradingSymbol": "SGMART",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SHAKTIPUMP": {
  "key": "NSE_EQ|INE908D01010",
  "tradingSymbol": "SHAKTIPUMP",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SHANKARA": {
  "key": "NSE_EQ|INE274V01019",
  "tradingSymbol": "SHANKARA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SHARDACROP": {
  "key": "NSE_EQ|INE221J01015",
  "tradingSymbol": "SHARDACROP",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SHARDAMOTR": {
  "key": "NSE_EQ|INE597I01028",
  "tradingSymbol": "SHARDAMOTR",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SHOPERSTOP": {
  "key": "NSE_EQ|INE498B01024",
  "tradingSymbol": "SHOPERSTOP",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SHREDIGCEM": {
  "key": "NSE_EQ|INE232A01011",
  "tradingSymbol": "SHREDIGCEM",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SMARTWORKS": {
  "key": "NSE_EQ|INE0NAZ01010",
  "tradingSymbol": "SMARTWORKS",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "SONATSOFTW": {
  "key": "NSE_EQ|INE269A01021",
  "tradingSymbol": "SONATSOFTW",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "STARHEALTH": {
  "key": "NSE_EQ|INE575P01011",
  "tradingSymbol": "STARHEALTH",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "STOVEKRAFT": {
  "key": "NSE_EQ|INE00IN01015",
  "tradingSymbol": "STOVEKRAFT",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SUPRAJIT": {
  "key": "NSE_EQ|INE399C01030",
  "tradingSymbol": "SUPRAJIT",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SURYAROSNI": {
  "key": "NSE_EQ|INE335A01020",
  "tradingSymbol": "SURYAROSNI",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "SYRMA": {
  "key": "NSE_EQ|INE0DYJ01015",
  "tradingSymbol": "SYRMA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TATATECH": {
  "key": "NSE_EQ|INE142M01025",
  "tradingSymbol": "TATATECH",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TCI": {
  "key": "NSE_EQ|INE688A01022",
  "tradingSymbol": "TCI",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TECHM": {
  "key": "NSE_EQ|INE669C01036",
  "tradingSymbol": "TECHM",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TEJASNET": {
  "key": "NSE_EQ|INE010J01012",
  "tradingSymbol": "TEJASNET",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TENNIND": {
  "key": "NSE_EQ|INE19RI01016",
  "tradingSymbol": "TENNIND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "THERMAX": {
  "key": "NSE_EQ|INE152A01029",
  "tradingSymbol": "THERMAX",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TIMETECHNO": {
  "key": "NSE_EQ|INE508G01029",
  "tradingSymbol": "TIMETECHNO",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "TRANSRAILL": {
  "key": "NSE_EQ|INE454P01035",
  "tradingSymbol": "TRANSRAILL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "TRITURBINE": {
  "key": "NSE_EQ|INE152M01016",
  "tradingSymbol": "TRITURBINE",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "V2RETAIL": {
  "key": "NSE_EQ|INE945H01021",
  "tradingSymbol": "V2RETAIL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "VAIBHAVGBL": {
  "key": "NSE_EQ|INE884A01027",
  "tradingSymbol": "VAIBHAVGBL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "VAML": {
  "key": "NSE_EQ|INE1CDF01017",
  "tradingSymbol": "VAML",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "VARROC": {
  "key": "NSE_EQ|INE665L01035",
  "tradingSymbol": "VARROC",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "VBL": {
  "key": "NSE_EQ|INE200M01039",
  "tradingSymbol": "VBL",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "VEDL": {
  "key": "NSE_EQ|INE205A01025",
  "tradingSymbol": "VEDL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "VIPIND": {
  "key": "NSE_EQ|INE054A01027",
  "tradingSymbol": "VIPIND",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "VIYASH": {
  "key": "NSE_EQ|INE807F01027",
  "tradingSymbol": "VIYASH",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "WAAREEENER": {
  "key": "NSE_EQ|INE377N01017",
  "tradingSymbol": "WAAREEENER",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "WOCKPHARMA": {
  "key": "NSE_EQ|INE049B01025",
  "tradingSymbol": "WOCKPHARMA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "WPIL": {
  "key": "NSE_EQ|INE765D01022",
  "tradingSymbol": "WPIL",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ZAGGLE": {
  "key": "NSE_EQ|INE07K301024",
  "tradingSymbol": "ZAGGLE",
  "series": "EQ",
  "joinedBy": "symbol+isin"
 },
 "ZENSARTECH": {
  "key": "NSE_EQ|INE520A01027",
  "tradingSymbol": "ZENSARTECH",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ZFCVINDIA": {
  "key": "NSE_EQ|INE342J01019",
  "tradingSymbol": "ZFCVINDIA",
  "series": "EQ",
  "joinedBy": "symbol"
 },
 "ZYDUSLIFE": {
  "key": "NSE_EQ|INE010B01027",
  "tradingSymbol": "ZYDUSLIFE",
  "series": "EQ",
  "joinedBy": "symbol"
 }
});

/** How many NSE symbols the dashboard can ask about, and how many are mapped above. */
export const UPSTOX_INSTRUMENT_COVERAGE = Object.freeze({"asked":162,"mapped":162,"unmapped":[]});
