// GENERATED by `npm run build-fund-navs` — do not edit by hand.
//
// AMFI's own published daily NAV, joined to this book ON THE ISIN. This is a
// PRICE SOURCE read at display time, exactly as a live quote is: it may move
// market value, day change, unrealised P&L and return on cost, and it may never
// touch quantity, cost basis, realised gains, dividends or any dated cash flow.
//
// It is NOT part of the book. `glowData.ts` is generated from `source/` and
// regenerates byte-identically; a fetched price may never enter it.

export interface FundNav {
  securityKey: string;
  security: string;
  /** The identifier the join was made on — exact, never a name match. */
  isin: string;
  /** Which tier supplied it: the family's own statement, or the look-through. */
  isinFrom: "statement" | "look-through";
  schemecode: string;
  scheme: string;
  plan: string;
  option: string;
  /** The NAV AMFI published, verbatim. */
  nav: number;
  /** Its own publication date — NOT the date the book's statements were drawn. */
  date: string;
  /** The NAV this file held on an earlier date, so a day change can be struck. */
  prev?: number;
  prevDate?: string;
  /** Null until this file has held two different dates — never a zero. */
  changePct: number | null;
  /**
   * Whether `quantity × nav` is a figure this book may publish. False where the
   * units and the NAV are not the same unit — see the builder's header.
   */
  usableForValue: boolean;
  /** Required whenever `usableForValue` is false. */
  notUsableReason: string | null;
}

export const BOOK_FUND_NAVS: FundNav[] = [
 {
  "securityKey": "absl-bal-adv-growth",
  "security": "ABSL BAL ADV-GROWTH",
  "isin": "INF084M01AB8",
  "isinFrom": "statement",
  "schemecode": "131666",
  "scheme": "Aditya Birla Sun Life Balanced Advantage Fund",
  "plan": "Regular Plan",
  "option": "GROWTH",
  "nav": 112.62,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "absl-liqf-d-growth",
  "security": "ABSL LIQF D-GROWTH",
  "isin": "INF209K01VA3",
  "isinFrom": "statement",
  "schemecode": "119568",
  "scheme": "Aditya Birla Sun Life Liquid Fund",
  "plan": "Direct Plan",
  "option": "GROWTH",
  "nav": 459.8003,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "bndh-l-and-mcf-dp-gr",
  "security": "BNDH L&MCF DP GR",
  "isin": "INF194K01V89",
  "isinFrom": "statement",
  "schemecode": "118419",
  "scheme": "Bandhan Large & Mid Cap Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 166.084,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "hdfc-baf-d-grow",
  "security": "HDFC BAF D-GROW",
  "isin": "INF179K01WA6",
  "isinFrom": "statement",
  "schemecode": "118968",
  "scheme": "HDFC Balanced Advantage Fund",
  "plan": "Direct Plan",
  "option": "Growth Option",
  "nav": 562.157,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "hdfc-baf-r-grow",
  "security": "HDFC BAF R-GROW",
  "isin": "INF179K01830",
  "isinFrom": "statement",
  "schemecode": "100119",
  "scheme": "HDFC Balanced Advantage Fund",
  "plan": "Regular Plan",
  "option": "Growth Option",
  "nav": 516.64,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "hdfc-liquid-fund-direct-plan-growth-option",
  "security": "HDFC Liquid Fund-Direct Plan-Growth Option",
  "isin": "INF179KB1HP9",
  "isinFrom": "statement",
  "schemecode": "119091",
  "scheme": "HDFC Liquid Fund",
  "plan": "Direct Plan",
  "option": "Growth Option",
  "nav": 5586.4803,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "hdfc-small-cap-fund-direct-growth-plan",
  "security": "HDFC Small Cap Fund - Direct Growth Plan",
  "isin": "INF179KA1RW5",
  "isinFrom": "statement",
  "schemecode": "130503",
  "scheme": "HDFC Small Cap Fund",
  "plan": "Direct Plan",
  "option": "Growth Option",
  "nav": 160.564,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "helios-fcf-d-grow",
  "security": "HELIOS FCF D-GROW",
  "isin": "INF0R8701046",
  "isinFrom": "statement",
  "schemecode": "152135",
  "scheme": "Helios Flexi Cap Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 16.16,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "helios-flexi-cap-fund-direct-growth",
  "security": "Helios Flexi Cap Fund - Direct Growth",
  "isin": "INF0R8701046",
  "isinFrom": "statement",
  "schemecode": "152135",
  "scheme": "Helios Flexi Cap Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 16.16,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "icici-ioppf-d-grw",
  "security": "ICICI IOPPF D-GRW",
  "isin": "INF109KC1RH9",
  "isinFrom": "statement",
  "schemecode": "145897",
  "scheme": "ICICI Prudential India Opportunities Fund",
  "plan": "Direct Plan",
  "option": "Cumulative",
  "nav": 39.23,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "icici-liqf-d-growth",
  "security": "ICICI LIQF D-GROWTH",
  "isin": "INF109K01Q49",
  "isinFrom": "statement",
  "schemecode": "120197",
  "scheme": "ICICI Prudential Liquid Fund -",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 420.9905,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "icici-nft-nt-50-dp-g",
  "security": "ICICI NFT NT 50 DP G",
  "isin": "INF109K01Y80",
  "isinFrom": "statement",
  "schemecode": "120684",
  "scheme": "ICICI Prudential Nifty Next 50 Index Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 67.1031,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "icici-nft-nx-50-r-gr",
  "security": "ICICI NFT NX 50 R GR",
  "isin": "INF109K01IF1",
  "isinFrom": "statement",
  "schemecode": "112957",
  "scheme": "ICICI Prudential Nifty Next 50 Index Fund",
  "plan": "Regular Plan",
  "option": "Growth",
  "nav": 63.3919,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "icici-nift50ind-dp-g",
  "security": "ICICI NIFT50IND DP G",
  "isin": "INF109K012M7",
  "isinFrom": "statement",
  "schemecode": "120620",
  "scheme": "ICICI Prudential Nifty 50 Index Fund",
  "plan": "Direct Plan",
  "option": "Cumulative",
  "nav": 247.8619,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "icici-pru-baf-dp-grw",
  "security": "ICICI PRU BAF DP GRW",
  "isin": "INF109K012B0",
  "isinFrom": "statement",
  "schemecode": "120377",
  "scheme": "ICICI Prudential Balanced Advantage Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 87.71,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "inves-con-r-growth",
  "security": "INVES CON R GROWTH",
  "isin": "INF205K01189",
  "isinFrom": "statement",
  "schemecode": "105460",
  "scheme": "Invesco India Contra Fund",
  "plan": "Regular Plan",
  "option": "Growth",
  "nav": 133.2,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "kotak-mtcf-d-grow",
  "security": "KOTAK MTCF D-GROW",
  "isin": "INF174KA1HV3",
  "isinFrom": "statement",
  "schemecode": "149185",
  "scheme": "Kotak Multi Cap Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 21.554,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "motilal-oswal-active-momentum-fund-direct-plan-growth-option",
  "security": "Motilal Oswal Active Momentum Fund - Direct Plan Growth Option",
  "isin": "INF247L01EP5",
  "isinFrom": "look-through",
  "schemecode": "153364",
  "scheme": "Motilal Oswal Active Momentum Fund",
  "plan": "Direct Plan",
  "option": "Growth",
  "nav": 14.5522,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "nip-etnf1d-rtliqbees",
  "security": "NIP ETNF1D RTLIQBEES",
  "isin": "INF732E01037",
  "isinFrom": "statement",
  "schemecode": "140086",
  "scheme": "Nippon India ETF Nifty 1D Rate Liquid BeES",
  "plan": "Direct Plan",
  "option": "",
  "nav": 1000,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 },
 {
  "securityKey": "woc-maaf-d-grow",
  "security": "WOC MAAF D-GROW",
  "isin": "INF03VN01761",
  "isinFrom": "statement",
  "schemecode": "151745",
  "scheme": "WhiteOak Capital Multi Asset Allocation Fund",
  "plan": "Direct Plan",
  "option": "Growth Option",
  "nav": 16.73,
  "date": "2026-09-21",
  "changePct": null,
  "usableForValue": true,
  "notUsableReason": null
 }
];

/** The newest publication date across every scheme above. */
export const FUND_NAV_AS_OF = "2026-09-21";
