// GENERATED by `npm run build-polycab` — DO NOT EDIT BY HAND.
//
// What the EXCHANGE and the statutory disclosures say about the ring-fenced
// promoter holding, refreshed daily by `.github/workflows/polycab.yml`. The
// builder's header explains every gate; the two that matter most here are:
//
//   • Everything from BSE is published only where the ISIN the exchange echoes
//     equals the ISIN `BOOK_POLYCAB` carries. A wrong scrip code answers with a
//     complete, correct table about another company.
//   • The promoter HOLDING has two independent witnesses and a disagreement
//     publishes neither. The promoter PLEDGE has one, and says so.
//
// NOTHING HERE IS IN ANY BOOK TOTAL. It is company-level and public; the
// family's own holding, its cost and its value stay in `BOOK_POLYCAB`, and the
// two are rendered in separate cards so that a promoter-GROUP encumbrance can
// never be read as a statement about THIS demat's balance.
//
// `docs/POLYCAB-LIVE.md` carries this run's findings.

export interface PolycabAction {
  exDate: string | null;
  kind: "dividend" | "bonus" | "split" | "spinoff" | "rights" | "other";
  purpose: string;
  amountPerShare: number | null;
  ratio: string | null;
  recordDate: string | null;
  bookClosureFrom: string | null;
  bookClosureTo: string | null;
  paymentDate: string | null;
}

export interface PolycabQuarter {
  /** `Jun 2026` — the label, derived from the quarter end and never scraped. */
  quarter: string | null;
  /** The quarter END the disclosure is struck at, ISO. */
  asOf: string;
  /** Null where the two witnesses disagreed — a REFUSAL, not a gap. */
  holdingPct: number | null;
  pledgePct: number | null;
  /** Which source carried the pledge, or null where none did. */
  pledgeSource: string | null;
  /** How many independent sources carried the holding for this quarter. */
  witnesses: number;
}

export interface PolycabQuote {
  ltp: number;
  prevClose: number | null;
  open: number | null;
  high: number | null;
  low: number | null;
  change: number | null;
  changePct: number | null;
  printedChange: number | null;
  printedChangePct: number | null;
}

export interface PolycabLive {
  scripCode: string;
  nseSymbol: string;
  bookIsin: string;
  bookShares: number | null;
  identity: {
    isin: string; scripCode: string | null; securityId: string | null;
    faceValue: number | null; industry: string | null; group: string | null; index: string | null;
  } | null;
  quote: PolycabQuote | null;
  corporateActions: PolycabAction[] | null;
  /** True only where THIS run fetched the exchange's whole record. A stored
   *  record kept through a failed fetch is never republished as complete, which
   *  is what lets the page say "none ever declared" as a measurement. */
  actionsComplete: boolean;
  promoterQuarters: PolycabQuarter[] | null;
  promoterAgreement: { compared: number; disagreed: number } | null;
  sources: { name: string; url: string; carries: string }[];
  notes: { severity: string; rule: string; detail: string }[];
  retrievedAt: string;
}

export const POLYCAB_LIVE: PolycabLive = {
  "scripCode": "542652",
  "nseSymbol": "POLYCAB",
  "bookIsin": "INE455K01017",
  "bookShares": 13901229,
  "identity": {
    "isin": "INE455K01017",
    "scripCode": "542652",
    "securityId": "POLYCAB",
    "faceValue": 10,
    "industry": "Cables - Electricals",
    "group": "A",
    "index": "BSE 200"
  },
  "quote": {
    "ltp": 8411.2,
    "prevClose": 8375,
    "open": 8376.65,
    "high": 8441.25,
    "low": 8376.65,
    "change": 36.20000000000073,
    "changePct": 0.43223880597015796,
    "printedChange": 36.2,
    "printedChangePct": 0.43
  },
  "corporateActions": [
    {
      "exDate": "2026-06-19",
      "kind": "dividend",
      "purpose": "Final Dividend - Rs. - 47.0000",
      "amountPerShare": 47,
      "ratio": null,
      "recordDate": "2026-06-19",
      "bookClosureFrom": null,
      "bookClosureTo": null,
      "paymentDate": "2026-07-30"
    },
    {
      "exDate": "2025-06-24",
      "kind": "dividend",
      "purpose": "Final Dividend - Rs. - 35.0000",
      "amountPerShare": 35,
      "ratio": null,
      "recordDate": "2025-06-24",
      "bookClosureFrom": null,
      "bookClosureTo": null,
      "paymentDate": "2025-07-31"
    },
    {
      "exDate": "2024-07-09",
      "kind": "dividend",
      "purpose": "Dividend - Rs. - 30.0000",
      "amountPerShare": 30,
      "ratio": null,
      "recordDate": null,
      "bookClosureFrom": "2024-07-10",
      "bookClosureTo": "2024-07-16",
      "paymentDate": null
    },
    {
      "exDate": "2023-06-21",
      "kind": "dividend",
      "purpose": "Dividend - Rs. - 20.0000",
      "amountPerShare": 20,
      "ratio": null,
      "recordDate": null,
      "bookClosureFrom": "2023-06-22",
      "bookClosureTo": "2023-06-25",
      "paymentDate": "2023-07-30"
    },
    {
      "exDate": "2022-06-21",
      "kind": "dividend",
      "purpose": "Dividend - Rs. - 14.0000",
      "amountPerShare": 14,
      "ratio": null,
      "recordDate": null,
      "bookClosureFrom": "2022-06-23",
      "bookClosureTo": "2022-06-29",
      "paymentDate": "2022-07-29"
    },
    {
      "exDate": "2021-07-12",
      "kind": "dividend",
      "purpose": "Dividend - Rs. - 10.0000",
      "amountPerShare": 10,
      "ratio": null,
      "recordDate": null,
      "bookClosureFrom": "2021-07-14",
      "bookClosureTo": "2021-07-21",
      "paymentDate": null
    },
    {
      "exDate": "2020-03-12",
      "kind": "dividend",
      "purpose": "Interim Dividend - Rs. - 7.0000",
      "amountPerShare": 7,
      "ratio": null,
      "recordDate": "2020-03-14",
      "bookClosureFrom": null,
      "bookClosureTo": null,
      "paymentDate": null
    },
    {
      "exDate": "2019-06-18",
      "kind": "dividend",
      "purpose": "Dividend - Rs. - 3.0000",
      "amountPerShare": 3,
      "ratio": null,
      "recordDate": null,
      "bookClosureFrom": "2019-06-20",
      "bookClosureTo": "2019-06-26",
      "paymentDate": null
    }
  ],
  "actionsComplete": true,
  "promoterQuarters": [
    {
      "asOf": "2026-06-30",
      "quarter": "Jun 2026",
      "holdingPct": 61.461685149737356,
      "pledgePct": 0,
      "pledgeSource": "tickertape",
      "witnesses": 2
    },
    {
      "asOf": "2026-03-31",
      "quarter": "Mar 2026",
      "holdingPct": 61.49620033165215,
      "pledgePct": 0,
      "pledgeSource": "tickertape",
      "witnesses": 2
    },
    {
      "asOf": "2025-12-31",
      "quarter": "Dec 2025",
      "holdingPct": 61.50111672781482,
      "pledgePct": 0,
      "pledgeSource": "tickertape",
      "witnesses": 2
    },
    {
      "asOf": "2025-09-30",
      "quarter": "Sep 2025",
      "holdingPct": 61.52122017376783,
      "pledgePct": 0,
      "pledgeSource": "tickertape",
      "witnesses": 2
    },
    {
      "asOf": "2025-06-30",
      "quarter": "Jun 2025",
      "holdingPct": 63.01064372395979,
      "pledgePct": 0,
      "pledgeSource": "tickertape",
      "witnesses": 2
    },
    {
      "asOf": "2025-03-31",
      "quarter": "Mar 2025",
      "holdingPct": 63.04426316271684,
      "pledgePct": 0,
      "pledgeSource": "tickertape",
      "witnesses": 2
    },
    {
      "asOf": "2024-12-31",
      "quarter": "Dec 2024",
      "holdingPct": 63.05,
      "pledgePct": null,
      "pledgeSource": null,
      "witnesses": 1
    },
    {
      "asOf": "2024-09-30",
      "quarter": "Sep 2024",
      "holdingPct": 63.06,
      "pledgePct": null,
      "pledgeSource": null,
      "witnesses": 1
    },
    {
      "asOf": "2024-06-30",
      "quarter": "Jun 2024",
      "holdingPct": 65.02,
      "pledgePct": null,
      "pledgeSource": null,
      "witnesses": 1
    },
    {
      "asOf": "2024-03-31",
      "quarter": "Mar 2024",
      "holdingPct": 65.24,
      "pledgePct": null,
      "pledgeSource": null,
      "witnesses": 1
    },
    {
      "asOf": "2023-12-31",
      "quarter": "Dec 2023",
      "holdingPct": 65.78,
      "pledgePct": null,
      "pledgeSource": null,
      "witnesses": 1
    },
    {
      "asOf": "2023-09-30",
      "quarter": "Sep 2023",
      "holdingPct": 65.91,
      "pledgePct": null,
      "pledgeSource": null,
      "witnesses": 1
    }
  ],
  "promoterAgreement": {
    "compared": 6,
    "disagreed": 0
  },
  "sources": [
    {
      "name": "BSE (exchange)",
      "url": "https://www.bseindia.com/stock-share-price/polycab-india-ltd/polycab/542652/",
      "carries": "identity, last traded price, the full corporate-action record"
    },
    {
      "name": "Tickertape",
      "url": "https://www.tickertape.in/stocks/polycab-india-POLC",
      "carries": "promoter holding and promoter pledge, per quarter — gated on the book's own ISIN"
    },
    {
      "name": "Screener",
      "url": "https://www.screener.in/company/POLYCAB/consolidated/",
      "carries": "promoter holding, per quarter — the second witness"
    }
  ],
  "notes": [
    {
      "severity": "info",
      "rule": "promoter-agreement",
      "detail": "6 quarter(s) carried by both witnesses; all agree within 0.05pp."
    }
  ],
  "retrievedAt": "2026-09-22T04:09:20.027Z"
};
