// GENERATED by `npm run reconcile:review` — do not edit by hand.
//
// Every line of the family's own consolidated review that NO NAME in this book
// reaches (section D of the report); the dashboard's own tiers withhold the ones
// a statement reports. It exists so a reader who searches this dashboard for
// one of these names is told why it is absent and which document would close
// it, rather than being shown an empty result they cannot tell from a defect.
//
// NOT ONE FIGURE OF THE REVIEW TRAVELS HERE. Since Stage 10dh the book carries
// the review's private-market lines through scripts/lib/reviewBook.mjs; every
// other review line is a cross-check. What travels here is a NAME, a custodian and
// two sentences — an absence and a document to ask for. There is deliberately
// no value and no quantity on this type, and the generator throws rather than
// emit one. Nothing here reaches `glowData.ts`, any total, or any allocation.

export interface ReviewGap {
  /** The review's own line name, verbatim. */
  name: string;
  /** Spellings the family use that the review does not print. Hand-checked. */
  aliases: string[];
  /** Where the review says it is held. Not a valuation. */
  custodian: string | null;
  /** Why this book carries no figure for it. */
  why: string;
  /** The one document that would close it. */
  ask: string;
}

/** The as-of the review calls itself, read from its own filename. */
export const REVIEW_AS_OF = "30 June 2026";

export const REVIEW_GAPS: ReviewGap[] = [
  {
    "name": "Aditya Birla SL Balanced Advantage Fund(G)",
    "aliases": [],
    "custodian": "MOPWM / MOPWM Dir",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Aditya Birla SL Liquid Fund-(DD)-Direct",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Aditya Birla SL Liquid Fund-Direct (G)",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Bandhan Large & Mid Cap Fund - Direct Plan - Growth",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Bharat Parenterals Ltd",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "BSE Ltd.",
    "aliases": [
      "Bombay Stock Exchange"
    ],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Deepak Fert",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "HDFC Balanced Advantage Fund",
    "aliases": [],
    "custodian": "MOPWM Dir / MOPWM Reg",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "HDFC Liquid Fund -Direct(G)",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "HDFC Overnight Fund - Direct - G",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "HSBC Liquid Fund-Direct(DD)",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "ICICI Pru Balanced Advantage Fund",
    "aliases": [],
    "custodian": "MOPWM Dir / MOPWM Reg",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "ICICI Pru India Opportunities Fund",
    "aliases": [],
    "custodian": "MOPWM Dir",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "ICICI Pru Liquid Fund-Direct(G)",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "ICICI Prudential Equity Savings Fund - Direct Plan",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "IFB Inds.",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Infinium Pharmachem Ltd.",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Invesco India Arbitrage Fund-Direct(G)",
    "aliases": [],
    "custodian": "Debt tab",
    "why": "a fund line on the Debt tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Invesco India Arbitrage Fund(G)",
    "aliases": [],
    "custodian": "Debt tab",
    "why": "a fund line on the Debt tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Kaynes Technology India ltd",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Kingfa Science & Technology Ltd.",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Kotak Equity Arbitrage Scheme(G)",
    "aliases": [],
    "custodian": "Debt tab",
    "why": "a fund line on the Debt tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Kotak Large & Midcap Fund - Direct- Growth",
    "aliases": [],
    "custodian": "MOPWM Dir",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Kotak Liquid-Direct (DD)",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Kotak Multicap Fund-Direct Plan-Growth",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Man Industries",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Manorama Industries Ltd.",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Mirae Asset Cash Management Fund-Direct(G)",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Motilal Oswal Arbitrage Fund Direct (G)",
    "aliases": [],
    "custodian": "Debt tab",
    "why": "a fund line on the Debt tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "Neuland Labs.",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Nippon India ETF Nifty 1D Rate Liquid Bees-IDCW",
    "aliases": [],
    "custodian": "Cash tab",
    "why": "a fund line on the Cash tab. What carries it is the AMC's own folio statement or a consolidated account statement (CAS) — not a demat holding statement, which moves units without a price",
    "ask": "AMC folio statements or a CAS for the mutual-fund and liquid holdings on the Debt / Cash / Alternate tabs"
  },
  {
    "name": "NLC INDIA",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Onesource Specialty Pharma",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Sterlite Grid 5",
    "aliases": [],
    "custodian": "HDFC Bank",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Sterlite Power Transmission",
    "aliases": [],
    "custodian": "HDFC Bank",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "STLNETWORK",
    "aliases": [],
    "custodian": "HDFC Bank",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Tatva Chintan Pharma Chem Limi",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Vedanta Iron & Steel Ltd",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Vedanta Oil & Gas Ltd",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "Vedanta Power Ltd",
    "aliases": [],
    "custodian": "HDFC Bank / MOPWM",
    "why": "held at HDFC Bank — no holding statement for Ajay's HDFC Bank demat is in the drop (Bharat's is a SCAN)",
    "ask": "HDFC Bank demat holding statements — Ajay's (none in the drop) and Bharat's as a text PDF, not a scan"
  },
  {
    "name": "WhiteOak Capital Multi Asset Allocation Fund-Direct(G)",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  },
  {
    "name": "Zaggle Prepaid Ocean Services Ltd.",
    "aliases": [],
    "custodian": "MOPWM",
    "why": "held at Motilal Oswal; the drop carries a holding statement for six of its seven demat accounts — quantities only, the rate being the price of the last movement — and only a transaction tape for Ajay's main demat",
    "ask": "Motilal Oswal holding statements for the demat and PWM accounts not in the drop"
  }
];
